# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters for grid search
logparser:
  method: ael # log parsing method
  parameters:
    minEventCount: # AEL minimum event count
      max: 20 # maximum
      min: 0 # minimum
      step: 1 # step size
    merge_percent: # AEL merge percentage
      max: 1
      min: 0
      step: 0.01