# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters for grid search
logparser:
  method: iplom # log parsing method
  parameters:
    step2Support: # IPLoM File Support Threshold
      max: 0.1
      min: 0
      step: 0.05
    PST: # IPLoM Partition Support Threshold --> algorithm breaks if > 0
      max: 0
      min: 0
      step: 1
    CT: # IPLoM Cluster Goodness Threshold
      max: 0.9
      min: 0.3
      step: 0.01
    lowerBound: # control thresholds for 1-M and M-1 relationships
      max: 0.5
      min: 0
      step: 0.01
    upperBound: # control thresholds for 1-M and M-1 relationships
      max: 0.9
      min: 0.9
      step: 0.1