# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters for grid search
logparser:
  method: spell # log parsing method
  parameters:
    tau: # Spell threshold for determining longest common subsequence
      max: 5 # maximum
      min: 0 # minimum
      step: 0.01 # step size