# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters
logparser:
  method: iplom # log parsing method
  parameters:
    maxEventLen: 200 # length of the longest log/event
    step2support: 0 # IPLoM File Support Threshold
    PST: 0 # IPLoM Partition Support Threshold
    CT: 0.35 # IPLoM Cluster Goodness Threshold
    lowerBound: 0.25 # control thresholds for 1-M and M-1 relationships
    upperBound: 0.9 # control thresholds for 1-M and M-1 relationships