# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters
logparser:
  method: iplom # log parsing method
  parameters:
    CT: 0.35 # IPLoM
    lowerBound: 0.25 # IPLoM