# log message format
log_format: "<Date> <Time> - <Level> - <Instrument> <Package>:<Line_Number> - <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  -

# log parsing method parameters
logparser:
  method: regex # log parsing method
  parameters:
    regex_templates: /Users/tyronevb/Documents/msc work 2020/datasets/mkat_cbf_0/cbf_corr2_servlet_templates_csv.csv # path to file containing regex templates