# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters
logparser:
  method: drain # log parsing method
  parameters:
    depth: 3 # drain parse tree depth
    st: 0.6 # drain similarity threshold
    maxChild: 100 # drain max number of child nodes