# log message format
log_format: "<Date> <Time> <Pid> <Level> <Component>: <Content>"

# pre-processing regex
preprocess: # supply all preprocessing regex
  - blk_-?\d+ # note how the regex is specified (not a raw string in the yaml file)
  - (\d+\.){3}\d+(:\d+)?

# log parsing method parameters
logparser:
  method: logmine # log parsing method
  parameters:
    max_dist: 0.001 # LogMine maximum distance between messages and representative cluster message
    k: 1 # LogMine clustering parameter
    k1: 1 # LogMine clustering parameter
    k2: 1 # LogMine clustering parameter
    alpha: 100 # LogMine factor by which to increase max dist for higher levels
    levels: 2 # LogMine max number of levels in the clustering hierarchy, (int)